setting:
  # Name of the lobby-world
  lobby-world: "world"

  # Delete old worlds folder after reset
  remove-old-worlds: true

  # Change motd of the server
  motd: true

  # The list of players who can bypass the death event
  user-bypass-list:
    - cykuta

  # If this is set to true, players who were offline while the world was reset
  # lose their inventory when they join again
  offline-player-inventory-clear: true

  # Lives a new game starts with
  max-lives: 3
